In [4]:
import numpy as np

two = np.array([
                [0, 0, 0, 0, 0, 0, 0],
                [0,+1,+1,+1,+1,+1, 0],
                [0, 0, 0, 0, 0,+1, 0],
                [0, 0, 0, 0, 0,+1, 0],
                [0,+1,+1,+1,+1,+1, 0],  
                [0,+1, 0, 0, 0, 0, 0],
                [0,+1, 0, 0, 0, 0, 0],
                [0,+1,+1,+1,+1,+1, 0],
                [0, 0, 0, 0, 0, 0, 0]])

nine=np.array([ 
                [0, 0, 0, 0, 0, 0, 0],
                [0,+1,+1,+1,+1,+1, 0],
                [0,+1, 0, 0, 0,+1, 0],
                [0,+1, 0, 0, 0,+1, 0],
                [0,+1,+1,+1,+1,+1, 0],
                [0, 0, 0, 0, 0,+1, 0],
                [0, 0, 0, 0, 0,+1, 0],
                [0, 0, 0, 0, 0,+1, 0],
                [0, 0, 0, 0, 0, 0, 0]
                ])

two = [2 * i - 1 for i in two]
nine = [2 * i - 1 for i in nine]
data = np.stack([two, nine])
# 次元数
dim = 63
# 記憶させたいパターン数
k = 2

'''
エネルギー関数E(x)から平衡状態(W_ij)を求める
'''
w = np.zeros([dim, dim])
print(w.shape)
for i in data:
    w += np.outer(i, i.T)
for i in range(dim):
    # 対角成分を0にする
    w[i][i] = 0
print(w)
    


(63, 63)
[[0. 2. 2. ... 2. 2. 2.]
 [2. 0. 2. ... 2. 2. 2.]
 [2. 2. 0. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 0. 2. 2.]
 [2. 2. 2. ... 2. 0. 2.]
 [2. 2. 2. ... 2. 2. 0.]]
